#! /usr/bin/php
<?php

require_once('addressFix.inc.php');

define('ATTRIBUTION', 'Orange County Open Data Portal');

function fixTags($tags) {
    $fixed = array();
    $fixed['building'] = 'yes';
    //$fixed['source:building'] = ATTRIBUTION;

    foreach ($tags as $key => $val) {
        switch ($key) {
            case 'ABS_HT':          // Convert from feet to meters.
                //$fixed['ele'] = round(($val+0.0)*0.3048,2);
                //$fixed['source:ele'] = ATTRIBUTION;
            break;

            case 'Address':
                $fixed = array_merge($fixed,parseAddress($val));
                //$fixed['OC:Address'] = $val;
                //$fixed['source:addr:housenumber'] = ATTRIBUTION;
                //$fixed['source:addr:street'] = ATTRIBUTION;
            break;

            case 'City':
                $fixed['addr:city'] = ucwords(strtolower($val));
                //$fixed['OC:City'] = $val;
                //$fixed['source:addr:city'] = ATTRIBUTION;
            break;

            case 'Height':          // Convert from feet to meters.
                $hgt = round(($val+0.0)*0.3048,2);
                if ($hgt > 2.0){
                    $fixed['height'] = $hgt;
                    //$fixed['source:height'] = ATTRIBUTION;
                }
                //$fixed['OC:Height'] = $val;
            break;

            case 'Zipcode':
                $fixed['addr:postcode'] = $val;
                //$fixed['source:addr:postcode'] = ATTRIBUTION;
            break;

            default:
                // printf('%s -> "%s"'.PHP_EOL, $key, $val);
            break;
        }
    }

    if (isset($fixed['addr:postcode'])) {
        if (isset($fixed['addr:city'])) {
            $fixed['addr:city'] = postalCity($fixed['addr:postcode'], $fixed['addr:city']);
        } else {
            $fixed['addr:city'] = postalCity($fixed['addr:postcode']);
        }
    }

    ksort($fixed);
    return $fixed;
}

$tags = array();
$line = fgets(STDIN);
while ($line !== false) {
    $line = trim($line);
    if (stripos($line,'<way ') !== false) {
        $tags = array();        // Reset object tags
    } else if (stripos($line,'<tag ') !== false) {
        $x = strtok($line, "'");
        $key = strtok("'");
        $x = strtok("'");
        $val = strtok("'");
        $tags[$key] = $val;
        $line = '';
    } else if (stripos($line,'</way>') !== false) {
        $fixed = fixTags($tags);
        foreach ($fixed as $k => $v) {
            printf("<tag k='%s' v='%s' />" . PHP_EOL, $k, $v);
        }
        $tags = array();
    }
    if (strlen($line) > 0) {
        printf("%s".PHP_EOL, $line);
    }
    $line = fgets(STDIN);
}

addressFixStats(STDERR);

?>
